### ISSUE TITLE
xiaomi.eu_multi_MI9_9.4.1 flash problem

### ISSUE THREAD

**Issue by maxwu124** [maboloshi/mipay-extract#3]
use TWRP to flash mipay-CEPHEUS_9.4.1.zip,
ERROR occured：Failed copy apps
Aborting...

**Comment by maboloshi** [comment]
Maybe the package you downloaded is corrupt. Please download again.

**Comment by maxwu124** [comment]
download again.
failed agian.

**Comment by maboloshi** [comment]
I can not reproduce this problem. Can you describe the process and your device model in detail?

**Comment by maxwu124** [comment]
我连magisk都没办法卸载 应该是twrp问题 你是什么版本twrp

**Comment by maboloshi** [comment]
@maxwu124 
可参考我的流程 https://gist.github.com/maboloshi/3316a78de3d9495387ff9d9050af010b

**Comment by maxwu124** [comment]
果然是twrp的问题 多谢指导

**Comment by maboloshi** [comment]
恩 我已经刷回 国内版，欧洲版 2个全家桶不见得省电
